### PR TITLE
WRT issue #5

### PR DESCRIPTION
**Pull request by charlessolar**
I see the problem with SimpleInjector is the freezing of the container, which is why you clone the builder I'm guessing.  And SI also has the problem of using PerInstance lifestyles with singletons which is understandable but silly.
So switching to SimpleInjector was not as easy I expected but it's rules do make sense.  I'm actually more frustrated with NSB's startup that constantly does resolutions and registrations...

But anyway, this patch removes the clone from CreateChildBuilder and increases performance by ~9x - I went from 75 msgs/s to >675 msgs/s
Cloneing is still used to register new objects after a resolution was made - which NSB does.  And a clone is also taken when you use `UseExistingContainer` too, which basically means once you initiate the bus you can't add anything to the container.  I thought that would be an issue but then remembered thats how SimpleInjector works anyway

### CODE REVIEW

**Comment by WilliamBZA** [comment]
Thanks for the PR @volak!

We could almost do away with the clone method completely. In V5.* of NSB, there was a need to be able to update a container that had already been configured. This requirement was actually removed in V6.0.0 of NSB, but there was still an acceptance test (from their sources) that tested that the container could be updated. The test was removed in V6.1.0 of NSB and I never got around to tweaking the code to remove the clone method.

The only reason to keep it around at all is to ensure that the correct properties are set on the container that is passed in to the `UseExistingContainer` method.  I wonder if it's reasonable to simply tell users that the container must be configured with `AllowOverridingRegistrations` set to true and that the `AutoWirePropertiesImplicitly()` extension method exposed in this lib should be called.

This would mean we could delete a whole bunch of code (and not have to maintain it!!) as long as we document that users should configure the containers passed in as follows:

```CSharp
var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
container.Options.AllowOverridingRegistrations = true;
container.Options.AutoWirePropertiesImplicitly();

endpointConfiguration.UseContainer<SimpleInjectorBuilder>(customization =>
{
    customization.UseExistingContainer(container);
});
```

The requirement is that the options are all configured as above.

What do you think? Is it reasonable to simply document that requirement? If yes, then we can actually delete **all** the cloning and cloning related code.

**Comment by charlessolar** [comment]
Deleting all the clone stuff sounds good to me - as for the doc, I would think it would be necessary to describe the requirement like above and do a check in code

```
if (!container.Options.AllowOverridingRegistrations)
    throw new ArgumentException("Invalid container - must set AllowOverridingRegistrations");
if (!(container.Options.DefaultScopedLifestyle is AsyncScopedLifestyle))
    throw new ArgumentException("Invalid container - must set DefaultScopedLifestyle 
 to AsyncScopedLifestyle");
if (!(container.Options.PropertySelectionBehavior is ImplicitPropertyInjectionBehavior))
     throw new ArgumentException("Invalid container - must set AutoWirePropertiesImplicitly");
```

When I tried this all I did firstly was delete `.Clone` and try it.  It seemed to me NSB was doing resolutions + registrations, even in 6.2 but its very highly probably it was actually me doing that and not NSB.

I seem to remember the problem was my endpoint was receiving and starting the pipeline on messages left in my queue before the endpoint was completely ready - but if so that would be a bug in NSB RabbitMq not here

**Comment by WilliamBZA** [comment]
Hmm, I'll double check on Rabbit but it should be fine. If it isn't that's likely a difference in behavior that really shouldn't be there just because of a transport choice.

In the meantime, would you mind changing the PR to remove the clone method and accessories completely? I'll run with the documentation changes and the rabbit tests.

**Comment by charlessolar** [comment]
Ok - I removed the clone pieces completely.
I added 1 test to verify a bad container not setup correctly throws an exception, but I'm afraid I'm not familiar enough with NSB's acceptance test framework to know how to write options in endpoint config.  Ideally I would have wanted to write 3 tests to verify all 3 exceptions are raised.

As far as rabbit, I tried this new binary and it worked fine - so I'm sure the exceptions I was seeing was just my inexperience and not knowing much about the SI locking.

**Comment by WilliamBZA** [comment]
Rabbit seems to be fine when I plug this container into the NSB.Rabbit acceptance tests.

I'll tweak the tests, we don't even need to dig into the acceptance test framework we can use unit tests for this.

**Comment by WilliamBZA** [comment]
[Here's](https://github.com/WilliamBZA/NServicebus.SimpleInjector/blob/master/src/NServiceBus.SimpleInjector.Tests/ExistingContainerConfigurationTests.cs) what I meant about using unit tests instead of the acceptance tests.

**Pull request merged**
